/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://i5tqvlfvcvbcram7gwg2cx4tqe.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dkd3hv4jeffbdlgukhytxbdc44",
    "aws_cognito_identity_pool_id": "us-west-1:b4539b77-6eff-46a1-a3ff-2a69c0a1d490",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_csEMKate6",
    "aws_user_pools_web_client_id": "961r5rmregumhikoibeuq4mj2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "aaaaa-dev",
    "aws_content_delivery_bucket_region": "us-west-1",
    "aws_content_delivery_url": "http://aaaaa-dev.s3-website-us-west-1.amazonaws.com"
};


export default awsmobile;
